services:
  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: orders_db

volumes:
  orders-db-data: